"card":{
            "msgtotal":"1",
            "title":"⻓⽂本-小号",
            "tcolor":"#3AA3E3",
            "url":"viewpage.action?pageId=9701578",
            "notice":"1",
            "click_to_delete":"1",
            "long_text":[
                {
                    "text":"⻓⽂本-小号",
                    "tcolor":"#3AA3E3",
                    "fontsize":"1",
                    "rows":"1",
                    "url":"long_text&type=card"
                }
            ]
        }

"card":{
            "msgtotal":"1",
            "title":"⻓⽂本-中号",
            "tcolor":"#3AA3E3",
            "url":"viewpage.action?pageId=9701578",
            "notice":"1",
            "click_to_delete":"1",
            "long_text":[
                {
                    "text":"⻓⽂本-中号",
                    "tcolor":"#3AA3E3",
                    "fontsize":"2",
                    "rows":"1",
                    "url":"long_text&type=card"
                }
            ]
        }

"card":{
            "msgtotal":"1",
            "title":"⻓⽂本-大号",
            "tcolor":"#3AA3E3",
            "url":"viewpage.action?pageId=9701578",
            "notice":"1",
            "click_to_delete":"1",
            "long_text":[
                {
                    "text":"⻓⽂本-大号",
                    "tcolor":"#3AA3E3",
                    "fontsize":"3",
                    "rows":"1",
                    "url":"long_text&type=card"
                }
            ]
        }

111111111111111111111111111111111


"card":{
            "msgtotal":"1",
            "title":"短⽂本-左对齐-小号",
            "tcolor":"#3AA3E3",
            "url":"viewpage.action?pageId=9701578",
            "notice":"1",
            "click_to_delete":"1",
            "short_text":[
                {
                    "text":"短⽂本-左对齐-小号",
                    "tcolor":"#3AA3E3",
                    "fontsize":"1",
                    "align":"1",
                    "url":"long_text&type=card"
                }
            ]
        }

"card":{
            "msgtotal":"1",
            "title":"短⽂本-居中-小号",
            "tcolor":"#3AA3E3",
            "url":"viewpage.action?pageId=9701578",
            "notice":"1",
            "click_to_delete":"1",
            "short_text":[
                {
                    "text":"短⽂本-居中-小号",
                    "tcolor":"#3AA3E3",
                    "fontsize":"1",
                    "align":"2",
                    "url":"long_text&type=card"
                }
            ]
        }

"card":{
            "msgtotal":"1",
            "title":"短⽂本-右边对齐-小号",
            "tcolor":"#3AA3E3",
            "url":"viewpage.action?pageId=9701578",
            "notice":"1",
            "click_to_delete":"1",
            "short_text":[
                {
                    "text":"短⽂本-右边对齐-小号",
                    "tcolor":"#3AA3E3",
                    "fontsize":"1",
                    "align":"2",
                    "url":"long_text&type=card"
                }
            ]
        }

"card":{
            "msgtotal":"1",
            "title":"短⽂本-右边对齐-中号",
            "tcolor":"#3AA3E3",
            "url":"viewpage.action?pageId=9701578",
            "notice":"1",
            "click_to_delete":"1",
            "short_text":[
                {
                    "text":"短⽂本-右边对齐-中号",
                    "tcolor":"#3AA3E3",
                    "fontsize":"2",
                    "align":"2",
                    "url":"long_text&type=card"
                }
            ]
        }

"card":{
            "msgtotal":"1",
            "title":"短⽂本-居中-大号",
            "tcolor":"#3AA3E3",
            "url":"viewpage.action?pageId=9701578",
            "notice":"1",
            "click_to_delete":"1",
            "short_text":[
                {
                    "text":"短⽂本-居中-大号",
                    "tcolor":"#3AA3E3",
                    "fontsize":"3",
                    "align":"2",
                    "url":"long_text&type=card"
                }
            ]
        }